---
name: Docker Latest Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Latest Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/blog
          tag_with_sha: true
          add_git_labels: true
          push: true

