baseURL = "https://blog.fraq.io"
languageCode = "en-us"
title = "Random Access Memetics"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = ""
    url = "/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
[[menu.main]]
    name = "Recommended Reading"
    url = "/recommended-reading/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    siteURL = "https://ram.fraq.io"
    description = "A place to learn about my memes"
    footer = "Built with [Hugo](https://gohugo.io/)  using [Hugo Classic](https://github.com/goodroot/hugo-classic)"
    custom_css = ["css/theme-override.css"]
