name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site using 
      run: |
        docker kill $(docker ps -q)
        docker build -t blog ${{ github.workspace }}
        docker run -p 80:1313 -d blog
